In [3]:
print('Hello World')

message = 'Hello World'
print(message)

Hello World
Hello World


In [0]:
print('What is you name?')
name = input()
print('Hello', name)

In [11]:
import numpy as np

x = np.array([1, 2, 3])

a = np.zeros((2, 2))

b = np.ones((2, 2))

z = a/b
print (z)

c = np.random.randint(10, size=(5))
print (c)

d = np.random.random((2, 2))
print (d)

e = np.array([1,2,3])
f = np.array([4,5,6])
g = np.add(e, f)
print (g)

[[0. 0.]
 [0. 0.]]
[2 3 9 3 9]
[[0.39320076 0.69543988]
 [0.09742614 0.76320565]]
[5 7 9]
