In [31]:
import numpy as np

A = np.matrix([[22, 5, 16, 9], [13, 20, 19, 0], [5, 9, 1, 16], [27, 13, 15, 19]])
B = np.matrix([[10, 5, 20, 20], [5, 21, 22, 27], [26, 19, 22, 3], [27, 8, 18, 7]])
# c = np.matrix([24, 3, 17, 7, 11, 2, 21, 2, 24, 18, 3, 11, 14, 25, 2, 20])
c = [24,3,17,7,11,2,21,2,24,18,3,11,14,25,2,20]
# d = np.matrix([3, 15, 24, 22, 19, 24, 4, 29, 6, 3, 20, 1, 11, 25, 26, 6])
d = [3,15,24,22,19,24,4,29,6,3,20,1,11,25,26,6]
print(A)
print(B)
print(c)
print(d)

e = np.add(A, B)
print("1. ", e)
f = np.subtract(A, B)
print("2. ", f)
g = np.divide(A, B)
print("3. ", g)
h = np.dot(A, B)
print("4. ", h)

i = np.add(c, d)
print("5. ", i)
j = np.subtract(c, d)
print("6. ", j)
k = np.multiply(c, d)
print("7. ", k)
l = np.dot(c,d)
print("8. ", l)

m = A + 10
print("9. ", m)
n = B + 10
print("10. ", n)
o = np.add(c, 15)
print("11. ", o)
p = np.add(d, 15)
print("12. ", p)

q = (2 * A) + (2 * B)
print("13. ", q)
r = (A + B) * 3
print("14. ", r)
s = (A - B + A - B + B) * 4
print("15. ", s)

[[22  5 16  9]
 [13 20 19  0]
 [ 5  9  1 16]
 [27 13 15 19]]
[[10  5 20 20]
 [ 5 21 22 27]
 [26 19 22  3]
 [27  8 18  7]]
[24, 3, 17, 7, 11, 2, 21, 2, 24, 18, 3, 11, 14, 25, 2, 20]
[3, 15, 24, 22, 19, 24, 4, 29, 6, 3, 20, 1, 11, 25, 26, 6]
1.  [[32 10 36 29]
 [18 41 41 27]
 [31 28 23 19]
 [54 21 33 26]]
2.  [[ 12   0  -4 -11]
 [  8  -1  -3 -27]
 [-21 -10 -21  13]
 [  0   5  -3  12]]
3.  [[2.2        1.         0.8        0.45      ]
 [2.6        0.95238095 0.86363636 0.        ]
 [0.19230769 0.47368421 0.04545455 5.33333333]
 [1.         1.625      0.83333333 2.71428571]]
4.  [[ 904  591 1064  686]
 [ 724  846 1118  857]
 [ 553  361  608  458]
 [1238  845 1498 1069]]
5.  [27 18 41 29 30 26 25 31 30 21 23 12 25 50 28 26]
6.  [ 21 -12  -7 -15  -8 -22  17 -27  18  15 -17  10   3   0 -24  14]
7.  [ 72  45 408 154 209  48  84  58 144  54  60  11 154 625  52 120]
8.  2298
9.  [[32 15 26 19]
 [23 30 29 10]
 [15 19 11 26]
 [37 23 25 29]]
10.  [[20 15 30 30]
 [15 31 32 37]
 [36 29 32 13]
 [37 1